# Generated by Django 2.2.7 on 2019-11-21 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191120_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 11, 57, 18, 77494, tzinfo=utc)),
        ),
    ]
